name: Check formatting with Prettier

on: push

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - run: pnpm exec prettier -c .
